### ISSUE TITLE
PA Review: Creating a new user / Being able to login / Guest Demo

### ISSUE THREAD

**Issue by Edwardc148** [Edwardc148/Jukebox#1]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: AJAX, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Looks great! Some minor details:

## Functionality 
- [x] Your logo, in this case, your h1 'jukebox' should redirect (on click) you to / or your splash. As of now is only text.
- [x] Handle cases when users try to access routes that do not exist, https://jukebox-aa.herokuapp.com/#/this-does-not-exist should redirect you to / or /login /singup etc..
- [x] It seems there is an issue with your reset.css import file `Failed to load resource: the server responded with a status of 404 (Not Found)   reset.css`.
- [x] Please remove the logging statements, looks like there is a `console.log(props)` somewhere.

## Style
- [x] Consider updating the :visited pseudoselector for 'anchor tags' , after visiting your Github link it turns to the regular 'purple', which does not contrast really well with a _blue-ish_ background.
- [x] The spacing between the start of the errors (login/signup) could take some top extra spacing.
- [x] Update the casing when there are login errors, `Invalid Username/Password Combination` to `Invalid username/password combination` or even something like 'Incorrect username or password.'
- [x] Consider opening an issue to add a transition when going from your splash to your main component.

**Comment by AAlfarho** [comment]
Assign this issue back to me when the updates are pushed to heroku.

**Comment by AAlfarho** [comment]
Great job, MVP is completed.
