### ISSUE TITLE
PA Review: Smooth Music Playback

### ISSUE THREAD

**Issue by Edwardc148** [Edwardc148/Jukebox#5]
- [x] Presentable styling
- [x] Able to move between same station without retrieving all music again
- [x] Able to change music when changing stations
- [x] Now playing button works
- [x] My stations button does not disrupt music playback
- [x] Play Pause Next Repeat
- [x] Adequate and appropriate seeds to test playback
- [x] Redux/React (appropriate action triggered on button clicks)

**Comment by AAlfarho** [comment]
Great job with the playback, smooth while navigating to your site, kudos!
The progress bar looks slick. Just a couple minor details before we can close this MVP down.

## Functionality
- [x] Remove console logs.

## Style
- [x] Remove the outline of your progress component.
With outline
![screen shot 2018-02-08 at 11 00 28 am](https://user-images.githubusercontent.com/1103663/35992787-28d2ea90-0cc0-11e8-8c62-5e572b4fe5b0.png)
Without outline
![screen shot 2018-02-08 at 11 00 14 am](https://user-images.githubusercontent.com/1103663/35992806-32e61ab6-0cc0-11e8-9d18-632f62ee09be.png)

Side Note: Isn't Avril Lavigne Sk8ter Boi in the album `Let Go`?  :)

Assign this back to me once the changes are pushed to the live version of the app.

**Comment by AAlfarho** [comment]
Great job on the new media player style, this MVP is almost complete.

- [x] Center your GitHub logo.

**Comment by Edwardc148** [comment]
- [x] centered github logo
