### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by Edwardc148** [Edwardc148/Jukebox#6]
- [x] Able to search up artists and songs
- [x] Able to provide suggestions upon failed search
- [x] Adequate and appropriate seeds
- [x] Smooth, bug-free navigation
- [x] Styling (looks presentable)

**Comment by AAlfarho** [comment]
Good job implementing the backend features of this search. The seeding is great and provides the app of a completeness feeling while searching. The debouncing feature helps us reduce some stress of our server by only querying our db when the user is ready.  Only a couple of styling details.

- [x] Consider the following template to base yourself upon. Pay close attention to the outline of the input (none), background, and padding. This is just an idea of the rules you should apply to your search bar.
![screen shot 2018-02-08 at 10 27 35 am](https://user-images.githubusercontent.com/1103663/35991057-d57638d4-0cba-11e8-8683-f05da481e12a.png)
Vs the original.
![screen shot 2018-02-08 at 10 27 23 am](https://user-images.githubusercontent.com/1103663/35991065-d9c17a0c-0cba-11e8-9824-4d472b3041ea.png)

**Comment by AAlfarho** [comment]
Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by AAlfarho** [comment]
Great job!

With the latest updates, this MVP is now complete.
